import { useState } from 'react';
import { Activity, AlertTriangle, BadgeCheck, BookOpen, ChevronRight, CircleUserRound, Database, FileClock, Flag, LayoutDashboard, MapPin, Menu, Search, Settings, ShieldCheck, Store, Users, X } from 'lucide-react';

const moderation = [
  { id: 'SIG-294', type: 'Prix extrême', title: '0,49 € · Pâte à tartiner 400 g', detail: 'Marché des Tamarins · signalé par CilaosRun', risk: 87, time: 'Il y a 8 min', tone: 'red' },
  { id: 'SIG-291', type: 'Commentaire', title: 'Contenu potentiellement personnel', detail: 'Signalé par 3 membres de la communauté', risk: 62, time: 'Il y a 24 min', tone: 'orange' },
  { id: 'MAG-088', type: 'Doublon magasin', title: 'Supermarché Savanna / Savanna Market', detail: 'Écart géographique : 18 mètres', risk: 54, time: 'Il y a 1 h', tone: 'yellow' },
];

const nav = [
  [LayoutDashboard, 'Vue d’ensemble'], [Flag, 'Modération'], [Store, 'Magasins'], [Users, 'Utilisateurs'], [Database, 'Sources'], [BadgeCheck, 'Badges & scores'], [FileClock, 'Journal d’audit'], [BookOpen, 'Documents légaux'], [Settings, 'Configuration'],
] as const;

export function App() {
  const [active, setActive] = useState('Vue d’ensemble');
  const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="shell">
    <aside className={mobileOpen ? 'sidebar open' : 'sidebar'}><button className="close" onClick={() => setMobileOpen(false)} aria-label="Fermer"><X /></button><div className="brand"><div className="brand-mark">P</div><div><strong>PrixPéi</strong><span>Administration</span></div></div><nav>{nav.map(([Icon, label]) => <button key={label} className={active === label ? 'active' : ''} onClick={() => { setActive(label); setMobileOpen(false); }}><Icon size={19}/><span>{label}</span>{label === 'Modération' && <b>7</b>}</button>)}</nav><div className="legal-note"><ShieldCheck size={22}/><div><strong>Accès journalisé</strong><span>Toute action sensible laisse une trace immuable.</span></div></div><div className="admin"><div className="avatar">AM</div><div><strong>Anaïs Martin</strong><span>Administratrice</span></div><ChevronRight size={17}/></div></aside>
    <main><header><button className="menu" onClick={() => setMobileOpen(true)} aria-label="Menu"><Menu/></button><div className="search"><Search size={18}/><input aria-label="Recherche" placeholder="Rechercher un prix, un magasin, un compte…"/></div><div className="status"><span></span> Tous les services opérationnels</div><button className="profile"><CircleUserRound size={22}/></button></header>
      <div className="content"><div className="welcome"><div><p className="eyebrow">Lundi 3 août 2026</p><h1>Bonjour Anaïs, voici l’essentiel.</h1><p>Supervisez la confiance de la communauté sans exposer ses données privées.</p></div><button className="primary"><Activity size={18}/>Voir l’activité en direct</button></div>
      <section className="metrics"><article><div className="metric-icon mint"><Flag/></div><span>À modérer</span><strong>7</strong><small><em>–3</em> depuis hier</small></article><article><div className="metric-icon coral"><AlertTriangle/></div><span>Signaux à risque</span><strong>3</strong><small>2 prioritaires</small></article><article><div className="metric-icon lavender"><Users/></div><span>Contributeurs actifs</span><strong>1 284</strong><small><em>+12 %</em> cette semaine</small></article><article><div className="metric-icon yellow"><MapPin/></div><span>Prix aujourd’hui</span><strong>842</strong><small>91 % publiés</small></article></section>
      <div className="grid"><section className="panel moderation"><div className="panel-head"><div><h2>File de modération</h2><p>Triée par niveau de risque interne.</p></div><button>Tout voir <ChevronRight size={16}/></button></div><div className="cases">{moderation.map((item) => <article className="case" key={item.id}><div className={`risk ${item.tone}`}>{item.risk}<span>/100</span></div><div className="case-main"><div className="tags"><span>{item.type}</span><small>{item.id}</small></div><h3>{item.title}</h3><p>{item.detail}</p></div><time>{item.time}</time><button className="review" onClick={() => alert(`Ouverture du dossier ${item.id}`)}>Examiner</button></article>)}</div></section>
      <aside className="panel health"><div className="panel-head"><div><h2>Santé des sources</h2><p>Contrôle et désactivation immédiate.</p></div></div><div className="source"><div className="source-logo off">OF</div><div><strong>Open Food Facts</strong><span>Produits & images</span></div><div className="source-state"><i></i>Active</div></div><div className="source"><div className="source-logo osm">OS</div><div><strong>OpenStreetMap</strong><span>Données géographiques</span></div><div className="source-state"><i></i>Active</div></div><div className="health-stats"><div><span>Cache produit</span><strong>98,7 %</strong></div><div><span>Erreurs / 24 h</span><strong>0,3 %</strong></div><div><span>Licence vérifiée</span><strong>03/08/26</strong></div></div><button className="secondary">Gérer les sources</button></aside></div>
      <section className="panel activity-panel"><div className="panel-head"><div><h2>Activité communautaire</h2><p>Contributions agrégées · aucune trajectoire individuelle.</p></div><select aria-label="Période"><option>7 derniers jours</option><option>30 derniers jours</option></select></div><div className="chart"><div className="ylabels"><span>1 000</span><span>750</span><span>500</span><span>250</span><span>0</span></div><div className="bars">{[55,67,61,79,72,88,93].map((height, index) => <div className="bar-col" key={index}><div className="bar" style={{height: `${height}%`}}><div className="bar-soft"/></div><span>{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'][index]}</span></div>)}</div></div></section>
      <footer>PrixPéi · Administration sécurisée · Les données antifraude ne sont jamais exposées publiquement.</footer></div>
    </main><div className={mobileOpen ? 'backdrop show' : 'backdrop'} onClick={() => setMobileOpen(false)}/>
  </div>;
}
