import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Header, Screen, Card, Pill } from '@/components/ui';
import { demoLeaderboard } from '@/lib/mock-data';
import { colors, radius } from '@/lib/theme';

export default function LeaderboardScreen() {
  const [period, setPeriod] = useState<'Semaine' | 'Mois'>('Semaine');
  return <Screen><Header eyebrow="Communauté" title="Les éclaireurs du coin" subtitle="Les contributions utiles font monter le classement, jamais l’activité seule." />
    <View style={styles.segment}>{(['Semaine', 'Mois'] as const).map((item) => <Pressable onPress={() => setPeriod(item)} key={item} style={[styles.segmentItem, period === item && styles.segmentActive]}><Text style={[styles.segmentText, period === item && styles.segmentTextActive]}>{item}</Text></Pressable>)}</View>
    <Card tone="sun"><View style={styles.area}><Ionicons name="location" size={22} color={colors.primaryDark} /><View style={{ flex: 1 }}><Text style={styles.areaLabel}>Classement local</Text><Text style={styles.areaValue}>Saint-Paul · 28 juil. – 3 août</Text></View><Ionicons name="chevron-down" size={19} color={colors.muted} /></View></Card>
    <View style={styles.podium}>{demoLeaderboard.slice(0, 3).map((user, index) => <View key={user.alias} style={[styles.podiumItem, index === 0 && styles.first]}><Text style={styles.badge}>{user.badge}</Text><View style={[styles.podiumAvatar, index === 0 && styles.avatarFirst]}><Text style={styles.initial}>{user.alias[0]}</Text></View><Text numberOfLines={1} style={styles.alias}>{user.alias}</Text><Text style={styles.points}>{user.points} pts</Text><Pill label={`#${user.rank}`} tone={index === 0 ? 'yellow' : 'neutral'} /></View>)}</View>
    <View style={styles.list}>{demoLeaderboard.slice(3).map((user) => <View key={user.alias} style={styles.row}><Text style={styles.rank}>{user.rank}</Text><View style={styles.smallAvatar}><Text style={styles.smallInitial}>{user.alias[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.rowAlias}>{user.alias}</Text><Text style={styles.areaValue}>{user.area}</Text></View><Text style={styles.rowPoints}>{user.points} pts</Text></View>)}</View>
    <Card tone="mint"><View style={styles.tip}><Ionicons name="sparkles" size={26} color={colors.mintDark} /><View style={{ flex: 1 }}><Text style={styles.tipTitle}>Votre prochaine action compte</Text><Text style={styles.tipText}>Confirmez un prix récent : +2 points provisoires après validation.</Text></View></View></Card>
    <Text style={styles.privacy}>Les classements utilisent uniquement les pseudonymes et sont masqués lorsque trop peu de personnes participent dans une zone.</Text>
  </Screen>;
}

const styles = StyleSheet.create({ segment: { flexDirection: 'row', backgroundColor: '#E9ECE8', padding: 4, borderRadius: radius.md }, segmentItem: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: 12 }, segmentActive: { backgroundColor: colors.white }, segmentText: { color: colors.muted, fontWeight: '800' }, segmentTextActive: { color: colors.ink }, area: { flexDirection: 'row', alignItems: 'center', gap: 12 }, areaLabel: { fontSize: 15, fontWeight: '900', color: colors.ink }, areaValue: { fontSize: 11, color: colors.muted, marginTop: 2 }, podium: { flexDirection: 'row', alignItems: 'flex-end', gap: 8, minHeight: 210 }, podiumItem: { flex: 1, alignItems: 'center', gap: 6, paddingVertical: 16, paddingHorizontal: 4, borderRadius: radius.lg, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, first: { minHeight: 205, backgroundColor: '#FFF8E5', borderColor: '#F4DE9C' }, badge: { fontSize: 22 }, podiumAvatar: { width: 55, height: 55, borderRadius: 21, backgroundColor: colors.lavender, alignItems: 'center', justifyContent: 'center' }, avatarFirst: { width: 66, height: 66, borderRadius: 24, backgroundColor: colors.sunshine }, initial: { fontSize: 23, fontWeight: '900', color: colors.ink }, alias: { fontWeight: '900', color: colors.ink, fontSize: 12 }, points: { color: colors.muted, fontSize: 11 }, list: { gap: 8 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: radius.lg, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, rank: { width: 20, fontWeight: '900', color: colors.muted, textAlign: 'center' }, smallAvatar: { width: 42, height: 42, borderRadius: 15, backgroundColor: '#E7F8EF', alignItems: 'center', justifyContent: 'center' }, smallInitial: { fontWeight: '900', color: colors.mintDark }, rowAlias: { fontWeight: '900', color: colors.ink }, rowPoints: { fontWeight: '900', color: colors.ink }, tip: { flexDirection: 'row', alignItems: 'center', gap: 13 }, tipTitle: { color: colors.ink, fontWeight: '900' }, tipText: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 4 }, privacy: { color: colors.muted, textAlign: 'center', fontSize: 11, lineHeight: 17, marginHorizontal: 16 },
});
