import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Header, Screen, SectionTitle, Pill } from '@/components/ui';
import { demoStores } from '@/lib/mock-data';
import { colors, radius } from '@/lib/theme';

export default function MapScreen() {
  const [radiusKm, setRadiusKm] = useState(10);
  return <Screen><Header eyebrow="Autour de moi" title="La carte des prix" subtitle="Les positions sont approximatives et votre localisation n’est pas conservée." />
    <View style={styles.filters}>{[5, 10, 20].map((value) => <Pressable key={value} onPress={() => setRadiusKm(value)} style={[styles.filter, radiusKm === value && styles.filterActive]}><Text style={[styles.filterText, radiusKm === value && styles.filterTextActive]}>{value} km</Text></Pressable>)}</View>
    <View style={styles.map} accessibilityLabel="Carte des magasins proches"><View style={styles.roadOne} /><View style={styles.roadTwo} /><View style={styles.sea}><Text style={styles.seaText}>Océan Indien</Text></View>{demoStores.map((store, index) => <View key={store.id} style={[styles.marker, { left: `${25 + index * 23}%`, top: `${24 + (index % 2) * 31}%` }]}><View style={styles.pin}><Text style={styles.pinPrice}>{['3,84', '3,95', '4,19'][index]} €</Text></View><View style={styles.pinTail} /></View>)}<View style={styles.you}><View style={styles.youCore} /></View><View style={styles.mapAttribution}><Text style={styles.attribution}>© contributeurs OpenStreetMap · rendu de démonstration</Text></View></View>
    <SectionTitle title={`${demoStores.length} magasins dans un rayon de ${radiusKm} km`} />
    {demoStores.map((store, index) => <View key={store.id} style={styles.store}><View style={[styles.number, index === 0 && styles.best]}><Text style={styles.numberText}>{index + 1}</Text></View><View style={{ flex: 1 }}><Text style={styles.storeName}>{store.name}</Text><Text style={styles.storeMeta}>{store.city} · {store.distanceKm} km</Text></View>{index === 0 ? <Pill label="Prix le plus bas" tone="green" /> : <Ionicons name="chevron-forward" size={20} color={colors.muted} />}</View>)}
  </Screen>;
}

const styles = StyleSheet.create({ filters: { flexDirection: 'row', gap: 8 }, filter: { paddingHorizontal: 17, paddingVertical: 9, borderRadius: 99, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, filterActive: { backgroundColor: colors.ink, borderColor: colors.ink }, filterText: { fontWeight: '800', color: colors.muted }, filterTextActive: { color: colors.white }, map: { height: 360, borderRadius: radius.xl, overflow: 'hidden', position: 'relative', backgroundColor: '#DDF0E4' }, roadOne: { position: 'absolute', width: 480, height: 24, backgroundColor: '#FFFDF4', top: 145, left: -50, transform: [{ rotate: '-18deg' }] }, roadTwo: { position: 'absolute', width: 390, height: 15, backgroundColor: '#FFFDF4', top: 210, left: 20, transform: [{ rotate: '50deg' }] }, sea: { position: 'absolute', width: 160, height: 440, right: -75, top: -40, backgroundColor: '#C9E7F3', transform: [{ rotate: '-8deg' }], justifyContent: 'center' }, seaText: { color: '#5A92A6', fontSize: 11, transform: [{ rotate: '8deg' }] }, marker: { position: 'absolute', alignItems: 'center' }, pin: { backgroundColor: colors.ink, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 12 }, pinPrice: { color: colors.white, fontSize: 12, fontWeight: '900' }, pinTail: { width: 0, height: 0, borderLeftWidth: 6, borderRightWidth: 6, borderTopWidth: 8, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderTopColor: colors.ink }, you: { position: 'absolute', left: '47%', top: '62%', width: 24, height: 24, borderRadius: 12, backgroundColor: 'rgba(255,91,69,.24)', alignItems: 'center', justifyContent: 'center' }, youCore: { width: 11, height: 11, borderRadius: 6, backgroundColor: colors.primary, borderWidth: 2, borderColor: colors.white }, mapAttribution: { position: 'absolute', bottom: 6, right: 6, backgroundColor: 'rgba(255,255,255,.85)', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 5 }, attribution: { fontSize: 8, color: colors.muted }, store: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: radius.lg, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, number: { width: 38, height: 38, borderRadius: 14, backgroundColor: '#EEF1EE', alignItems: 'center', justifyContent: 'center' }, best: { backgroundColor: colors.mint }, numberText: { fontWeight: '900', color: colors.ink }, storeName: { fontWeight: '900', color: colors.ink, fontSize: 14 }, storeMeta: { color: colors.muted, fontSize: 12, marginTop: 3 },
});
