import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { contributorLevel } from '@prixpei/domain';
import { Button, Card, Header, Pill, Screen, SectionTitle } from '@/components/ui';
import { colors, radius } from '@/lib/theme';
import { useSessionStore } from '@/store/session';

const MenuRow = ({ icon, label, value, onPress }: { icon: keyof typeof Ionicons.glyphMap; label: string; value?: string; onPress?: () => void }) => <Pressable onPress={onPress} style={styles.menuRow}><View style={styles.menuIcon}><Ionicons name={icon} size={20} color={colors.ink} /></View><Text style={styles.menuLabel}>{label}</Text>{value ? <Text style={styles.menuValue}>{value}</Text> : null}<Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable>;

export default function ProfileScreen() {
  const session = useSessionStore();
  if (session.isGuest) return <Screen><Header eyebrow="Votre espace" title="Contribuez, gagnez des badges." subtitle="Votre contexte est conservé lorsque vous créez votre compte après une action." /><Card tone="mint"><View style={styles.guestArt}><Text style={styles.guestEmoji}>🌱</Text><Text style={styles.guestTitle}>Commencez en quelques secondes</Text><Text style={styles.guestText}>Publiez, confirmez et commentez les prix. Votre email et votre position exacte ne sont jamais publics.</Text></View></Card><Button label="Créer mon compte" icon="sparkles" onPress={() => router.push('/auth')} /><Button label="Continuer en invité" variant="secondary" onPress={() => router.push('/')} /></Screen>;
  const level = contributorLevel(740);
  return <Screen><Header eyebrow="Mon profil" title={session.alias ?? 'Mon profil'} subtitle={`${level.title} · Niveau ${level.level}`} action={<Pressable onPress={() => router.push('/settings')} style={styles.settings}><Ionicons name="settings-outline" size={22} color={colors.ink} /></Pressable>} />
    <Card tone="mint"><View style={styles.hero}><View style={styles.profileAvatar}><Text style={styles.profileInitial}>{session.alias?.[0] ?? 'P'}</Text><View style={styles.online} /></View><View style={{ flex: 1 }}><Pill label="Contributeur fiable" tone="green" icon="shield-checkmark" /><Text style={styles.reliability}>Fiabilité 86 %</Text><View style={styles.progress}><View style={[styles.progressFill, { width: `${level.progress * 100}%` }]} /></View><Text style={styles.next}>60 points avant le niveau suivant</Text></View></View></Card>
    <View style={styles.stats}><Card style={styles.stat}><Text style={styles.statValue}>680</Text><Text style={styles.statLabel}>points validés</Text></Card><Card style={styles.stat}><Text style={styles.statValue}>60</Text><Text style={styles.statLabel}>provisoires</Text></Card><Card style={styles.stat}><Text style={styles.statValue}>42</Text><Text style={styles.statLabel}>prix aidés</Text></Card></View>
    <SectionTitle title="Mes badges" action="Tout voir" /><View style={styles.badges}>{[['🧭', 'Éclaireur'], ['✅', 'Œil fiable'], ['🌋', 'Expert local']].map(([emoji, title]) => <View key={title} style={styles.badge}><Text style={styles.badgeEmoji}>{emoji}</Text><Text style={styles.badgeTitle}>{title}</Text></View>)}</View>
    <SectionTitle title="Mon activité" /><View style={styles.menu}><MenuRow icon="receipt-outline" label="Mes signalements" value="18" /><MenuRow icon="checkmark-circle-outline" label="Mes confirmations" value="24" /><MenuRow icon="time-outline" label="En attente de synchro" value="0" /><MenuRow icon="trophy-outline" label="Mon classement" value="#12" /></View>
    <Button label="Se déconnecter" variant="ghost" onPress={session.signOut} />
  </Screen>;
}

const styles = StyleSheet.create({ settings: { width: 46, height: 46, borderRadius: 16, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line }, guestArt: { alignItems: 'center', gap: 10, paddingVertical: 20 }, guestEmoji: { fontSize: 58 }, guestTitle: { fontSize: 21, fontWeight: '900', color: colors.ink }, guestText: { color: colors.muted, textAlign: 'center', lineHeight: 21 }, hero: { flexDirection: 'row', alignItems: 'center', gap: 15 }, profileAvatar: { width: 72, height: 72, borderRadius: 25, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, profileInitial: { color: colors.white, fontSize: 29, fontWeight: '900' }, online: { position: 'absolute', width: 15, height: 15, borderRadius: 8, backgroundColor: '#34C98A', borderWidth: 3, borderColor: '#E7F8EF', right: -2, bottom: 5 }, reliability: { color: colors.ink, fontWeight: '900', fontSize: 17, marginTop: 10 }, progress: { height: 7, borderRadius: 4, backgroundColor: '#CDE8D9', overflow: 'hidden', marginTop: 8 }, progressFill: { height: '100%', backgroundColor: colors.mintDark, borderRadius: 4 }, next: { color: colors.muted, fontSize: 10, marginTop: 5 }, stats: { flexDirection: 'row', gap: 9 }, stat: { flex: 1, padding: 13, minHeight: 90, justifyContent: 'center' }, statValue: { color: colors.ink, fontSize: 21, fontWeight: '900' }, statLabel: { color: colors.muted, fontSize: 10, marginTop: 4 }, badges: { flexDirection: 'row', gap: 9 }, badge: { flex: 1, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 12, alignItems: 'center', gap: 7 }, badgeEmoji: { fontSize: 28 }, badgeTitle: { color: colors.ink, fontSize: 10, fontWeight: '800', textAlign: 'center' }, menu: { backgroundColor: colors.white, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, overflow: 'hidden' }, menuRow: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, menuIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center' }, menuLabel: { flex: 1, color: colors.ink, fontWeight: '700', fontSize: 14 }, menuValue: { color: colors.muted, fontWeight: '800' },
});
