import { Alert, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { formatObservedAt, trustLabel } from '@prixpei/domain';
import { Button, Card, Pill, Screen, SectionTitle } from '@/components/ui';
import { demoPrices } from '@/lib/mock-data';
import { colors, radius } from '@/lib/theme';
import { useSessionStore } from '@/store/session';

export default function PriceDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const report = demoPrices.find((item) => item.id === id) ?? demoPrices[0]!;
  const session = useSessionStore();
  const requireAuth = (label: string, action: () => void) => { if (session.isGuest) { session.setPendingAction({ path: `/price/${report.id}`, label }); router.push('/auth'); } else action(); };
  const confirm = () => requireAuth('confirmer ce prix', () => Alert.alert('Merci !', 'Votre confirmation est enregistrée. Les points restent provisoires jusqu’au contrôle serveur.'));
  return <Screen><View style={styles.hero}><Pill label="Prix signalé par la communauté" tone="green" icon="people" /><Text style={styles.price}>{report.price.toFixed(2).replace('.', ',')} €</Text><Text style={styles.store}>{report.store.name}</Text><Text style={styles.address}>{report.store.address}, {report.store.city}</Text><View style={styles.metaRow}><Pill label={formatObservedAt(report.observedAt)} /><Pill label={`${report.store.distanceKm} km`} /></View></View>
    <Card tone={report.trustScore >= 80 ? 'mint' : 'sun'}><View style={styles.trust}><View style={styles.gauge}><Text style={styles.gaugeValue}>{report.trustScore}</Text><Text style={styles.gaugeMax}>/100</Text></View><View style={{ flex: 1 }}><Text style={styles.trustTitle}>{trustLabel(report.trustScore)}</Text><Text style={styles.trustText}>Ce score combine la fraîcheur, la réputation et les validations indépendantes. Ce n’est pas une garantie.</Text></View></View><View style={styles.voteRow}><View><Text style={styles.voteValue}>{report.confirmations}</Text><Text style={styles.voteLabel}>confirmations</Text></View><View><Text style={styles.voteValue}>{report.disputes}</Text><Text style={styles.voteLabel}>contestation</Text></View><View><Text style={styles.voteValue}>86 %</Text><Text style={styles.voteLabel}>réputation moyenne</Text></View></View></Card>
    {report.loyaltyOnly ? <Card tone="sun"><View style={styles.condition}><Ionicons name="card" size={23} color={colors.primaryDark} /><View><Text style={styles.conditionTitle}>Prix fidélité</Text><Text style={styles.conditionText}>{report.conditions}</Text></View></View></Card> : null}
    <View style={styles.actions}><Button label="Je confirme ce prix" icon="checkmark-circle" onPress={confirm} /><Button label="Le prix a changé" icon="swap-horizontal" variant="secondary" onPress={() => requireAuth('corriger ce prix', () => Alert.alert('Correction', 'Le formulaire de nouveau prix va s’ouvrir.'))} /><Button label="Produit indisponible" icon="alert-circle-outline" variant="ghost" onPress={() => requireAuth('signaler une indisponibilité', () => Alert.alert('Signalement reçu'))} /></View>
    <SectionTitle title="Commentaires utiles" action="Ajouter" onAction={() => requireAuth('ajouter un commentaire', () => Alert.alert('Commentaire', 'Le champ de commentaire est disponible dans la version connectée.'))} />
    <View style={styles.comment}><View style={styles.commentAvatar}><Text style={styles.commentInitial}>M</Text></View><View style={{ flex: 1 }}><Text style={styles.commentAuthor}>MayaPéi · il y a 35 min</Text><Text style={styles.commentText}>Prix vu au rayon petit-déjeuner, encore plusieurs pots disponibles.</Text></View></View>
    <Text style={styles.author}>Signalé par {report.authorAlias}. La position exacte du contributeur n’est jamais publiée.</Text>
  </Screen>;
}

const styles = StyleSheet.create({ hero: { alignItems: 'center', gap: 7, paddingTop: 12 }, price: { fontSize: 52, lineHeight: 60, color: colors.ink, fontWeight: '900', letterSpacing: -2 }, store: { fontSize: 20, fontWeight: '900', color: colors.ink }, address: { color: colors.muted, fontSize: 12, textAlign: 'center' }, metaRow: { flexDirection: 'row', gap: 7, marginTop: 8 }, trust: { flexDirection: 'row', alignItems: 'center', gap: 14 }, gauge: { width: 72, height: 72, borderRadius: 25, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, gaugeValue: { fontSize: 24, fontWeight: '900', color: colors.mintDark }, gaugeMax: { fontSize: 9, color: colors.muted }, trustTitle: { fontSize: 17, fontWeight: '900', color: colors.ink }, trustText: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 4 }, voteRow: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#CDE8D9', marginTop: 16, paddingTop: 14 }, voteValue: { fontWeight: '900', color: colors.ink, textAlign: 'center' }, voteLabel: { color: colors.muted, fontSize: 9, marginTop: 2, textAlign: 'center' }, condition: { flexDirection: 'row', gap: 12, alignItems: 'center' }, conditionTitle: { color: colors.ink, fontWeight: '900' }, conditionText: { color: colors.muted, fontSize: 12, marginTop: 2 }, actions: { gap: 9 }, comment: { flexDirection: 'row', gap: 11, padding: 15, backgroundColor: colors.white, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line }, commentAvatar: { width: 40, height: 40, borderRadius: 14, backgroundColor: colors.lavender, alignItems: 'center', justifyContent: 'center' }, commentInitial: { color: colors.ink, fontWeight: '900' }, commentAuthor: { color: colors.ink, fontWeight: '800', fontSize: 12 }, commentText: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 4 }, author: { textAlign: 'center', color: colors.muted, fontSize: 10, lineHeight: 15 },
});
